[package]
name = "circuit-breaker-labs"
version = "0.1.8"
edition = "2024"
build = "build.rs"
description = "Circuit Breaker Labs command-line interface"
repository = "https://github.com/circuitbreakerlabs/cli"
homepage = "https://github.com/circuitbreakerlabs/cli"
documentation = "https://api.circuitbreakerlabs.ai/v1/docs"

[[bin]]
name = "cbl"
path = "./src/main.rs"

[lints.clippy]
pedantic = "deny"

[dependencies]
async-openai = { version = "0.32.4", default-features = false, features = ["chat-completion", "rustls"] }
async-trait = "0.1.89"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.5.57", features = ["derive", "env"] }
const_format = "0.2.35"
env = "1.0.1"
futures-util = "0.3.31"
ollama-rs = { version = "0.3.4", default-features = false, features = ["headers", "rustls"] }
ratatui = "0.30.0"
reqwest = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }
rhai = { version = "1.21", features = ["serde", "sync"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tabled = "0.16"
thiserror = "2.0.18"
tokio = { version = "1.49.0", features = ["full"] }
tokio-tungstenite = { version = "0.28.0", features = ["rustls-tls-native-roots"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
url = "2.5.8"
update-informer = { version = "1.1", default-features = false, features = ["github", "reqwest", "rustls-tls"] }

[build-dependencies]
anyhow = "1.0.100"
vergen = "10.0.0-beta.5"
vergen-gitcl = "10.0.0-beta.5"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
